version: '3.8'
services:
  minio:
    image: minio/minio:latest
    command: server /data
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
    volumes:
      - ./storage/docker/minio-data:/data
    networks:
      - backend

networks:
  backend:
