version: '3.8'
services:
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./storage/docker/minio-data:/data
